name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git clone vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git  
        cd vcpkg
    - name: bootstrap-vcpkg.sh
      run: |
        ./bootstrap-vcpkg.sh
    - name: vcpkg integrate install
      run: |
        ./vcpkg integrate install
    - name: vcpkg install libevent
      run: |
        ./vcpkg install libevent
        
    - name: install bootymapper
      run: |
        git clone https://github.com/shishohf/bootymapper.git
        cd bootymapper
        make
        
