name: ubuntu test
on:
  push:
    branches: [ master]

jobs:
  ubuntu:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - name: build
#       run: |
#           git clone https://github.com/Microsoft/vcpkg.git  
#           cd vcpkg
#           ./bootstrap-vcpkg.sh
#           ./vcpkg integrate install
#           ./vcpkg install libevent
    - name: inatall firefox-esr
      run: |
        sudo apt update
        sudo apt install firefox-esr

        


