name: ubuntu test
on:
  push:
    branches: [ master]

jobs:
  ubuntu:  
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        AA: [aa,bb]
    steps:
    - uses: actions/checkout@v2
#     - name: build
#       run: |
#           git clone https://github.com/Microsoft/vcpkg.git  
#           cd vcpkg
#           ./bootstrap-vcpkg.sh
#           ./vcpkg integrate install
#           ./vcpkg install libevent
    - name: inatall firefox-esr
      run: |
        pwd
#       if: matrix.AA == 'aa'
      if: "contains(matrix.AA, 'aa')"
  

        


