name: ubuntu test
on:
  push:
    branches: [ master]

jobs:
  ubuntu:  
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        AA: [aa,bb]
    steps:
    - uses: actions/checkout@v2
#     - name: build
#       run: |
#           git clone https://github.com/Microsoft/vcpkg.git  
#           cd vcpkg
#           ./bootstrap-vcpkg.sh
#           ./vcpkg integrate install
#           ./vcpkg install libevent
    - name: inatall firefox-esr
      shell: bash
      run: |
        if [ "${{ matrix.AA }}" == "aa" ]; then
          export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-esr-latest&lang=en-US&os=linux64'
          wget --no-verbose $FIREFOX_SOURCE_URL -O - | tar -jx -C ${HOME}
          export PATH=${HOME}/firefox:$PATH
        fi
        ls ${HOME}/firefox
#        firefox --version
#       if: matrix.AA == 'aa'
      if: "contains(matrix.AA, 'aa')"
    - name: aaaaa
      if: "contains(matrix.AA, 'aa')"
      env:
        PATH: ${PATH}:aaaa
      run: |
        echo $PATH
            
