name: autotools on windows

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  windows2016:
    runs-on: windows-latest
    strategy:
      matrix:
        EVENT_BUILD_METHOD: [autotools]
        EVENT_MATRIX: [""]    

    steps:      
    - uses: actions/checkout@v1
    - uses: numworks/setup-msys2@v1
      with: 
    # Variant of the environment to set by default: MSYS, MINGW32 or MINGW64
        msystem: MINGW64
    - run: |
        if (( "${{ matrix.EVENT_MATRIX }}" -eq "" ) -and ( ${{ matrix.EVENT_BUILD_METHOD }} -eq cmake )) {
          $EVENT_CMAKE_OPTIONS=""
        } else {
          $EVENT_CONFIGURE_OPTIONS=""
        }

        $env:EVENT_BUILD_METHOD='autotools'
        if ($env:EVENT_BUILD_METHOD -eq 'autotools') {
        $script=@'
        [[ $? -ne 0 ]] && exit 1
        mkdir build-autotools 2>/dev/null
        cd build-autotools
        [[ $? -ne 0 ]] && exit 1
        pwd
        [[ $? -ne 0 ]] && exit 1
        pwd
        '@
        D:\a\_temp\msys\\msys64\usr\bin\bash.exe -c -l $script
        }

        


