name: autotools on windows

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  windows2016:
    runs-on: windows-latest
    strategy:
      matrix:
        EVENT_BUILD_METHOD: [autotools]
        EVENT_MATRIX: [""]    

    steps:      
    - uses: actions/checkout@v1
    - uses: numworks/setup-msys2@v1
      with: 
    # Variant of the environment to set by default: MSYS, MINGW32 or MINGW64
        msystem: MINGW64
    - run: |
        pwd
    - name: build
      shell: bash
      run: |
        MPATH="/d/a/_temp/msys/msys64/usr/bin"
        PATH="${MPATH}:${PATH}"
        echo ${PATH}
    - name: test
      shell: bash
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-gcc
        pwd
        mkdir build-autotools 
        cd build-autotools 
        pwd
        


