name: autotools on windows

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  windows2016:
    runs-on: windows-latest
    strategy:
      matrix:
        EVENT_BUILD_METHOD: [autotools]
        EVENT_MATRIX: [""]    

    steps:      
    - uses: actions/checkout@v1
    - uses: numworks/setup-msys2@v1
      with: 
    # Variant of the environment to set by default: MSYS, MINGW32 or MINGW64
        msystem: MINGW64
    - run: |
          msys2do pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-freetype mingw-w64-x86_64-pkg-config make mingw-w64-x86_64-python3 mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-libpng
          msys2do set MSYSTEM=MINGW64
          msys2do pwd
          msys2do mkdir build-autotools 
          msys2do cd build-autotools 


