name: vcpkg test

on:
  pull_request:
    types: [opened, synchronize]
  # push:
  #   branches:
  #   - master
  #   tags:
  #   - '*'

jobs:
  windows2019:
    runs-on: windows-2019
    strategy:
      matrix:
        EVENT_BUILD_METHOD: [cmake]
        EVENT_MATRIX: [""]    

    steps:      
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v2.1.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: .github
        # An explicit key for restoring and saving the cache
        key: mingw-cmake-${{ matrix.EVENT_BUILD_METHOD }}-${{ job.container }}
    - name: vcpkg
      run: |
        echo $env:PATH
        vcpkg install libevent:x64-windows-static


 
